server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.kcnoyckvyxifooitkbhu
    password: BillBridge@0209
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

supabase:
  url: https://kcnoyckvyxifooitkbhu.supabase.co
  service-role-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjbm95Y2t2eXhpZm9vaXRrYmh1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTU3NDU5MSwiZXhwIjoyMDg3MTUwNTkxfQ.HHWu5CBHaBIWrHHcAVD2DYEFtIpEP0PDoNMuFbxRxGA
  bucket: bills
    
paytm:
  merchant-id: tXvhzx31620803258735
  merchant-key: snZDiqGM3sEfN@Rp

logging:
    level:
        com:
          paytm: OFF
        paytm:
          pg: OFF

security:
  jwt:
    secret: Oc4W/lmEDbpRTZqD0vvlgznr0lNmE/IQARsQPt7RIvgD6Ye9RktGv9+y2dn4RKkQwmVeQFbNw9/Zu0Eq66/gkg==
    issuer: Bill-Bridge
    access-token-expiration: 60000 # 1 minute in milliseconds  
    refresh-token-expiration: 240000 # 4 min in millisec
    refresh-token-cookie-name: refreshToken
    cookie-secure: true
    cookie-http-only: true
    cookie-same-site: lax
    cookie-domain: localhost
    



